### ISSUE TITLE
Initial code commit

### ISSUE THREAD

**Issue by gm7** [GrindrodBank/tilkynna#1]
We need the initial report service code committed to this repo.

**Comment by melissapalmer** [comment]
This has now been done, 
- GitHub repo : https://github.com/GrindrodBank/tilkynna
- Docker Hub : https://hub.docker.com/r/grindrodbank/tilkynna
- CircleCi : https://circleci.com/gh/GrindrodBank/workflows/tilkynna
- FOSSA : https://app.fossa.com/projects/git+github.com/GrindrodBank/tilkynna/refs/branch/master/1e1fd99108fc9010ace40b6cab777877afbe6df3
- SonarQUbe : https://sonarcloud.io/dashboard?id=Grindrodbank_tilkynna
