### ISSUE TITLE
Helm references in the documentation

### ISSUE THREAD

**Issue by gm7** [GrindrodBank/tilkynna#8]
**Describe the bug**
There are references to Helm in the documentation, but there are no Helm charts in this repo. 

**To Reproduce**
The following files have references to Helm:

1. pom-rat.xml
2. doc/contributing/testing_locally.md
3. doc/report_generation.md

**Expected behavior**
There should be no references to Helm in our documenatation, since there are no project artifacts in the repo that relate to Helm.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
No other related information

**Comment by melissapalmer** [comment]
This as been corrected by PR #11
