### ISSUE TITLE
Postman Environment

### ISSUE THREAD

**Issue by gm7** [GrindrodBank/tilkynna#9]
**Describe the bug**
The [postman environment file](https://github.com/GrindrodBank/tilkynna/blob/master/postman/Tilkynna.postman_environment.json) does not work with the quick start.

**To Reproduce**
1. Run [the Quick start](https://github.com/GrindrodBank/tilkynna/tree/master/quickstart/docker-compose)
2. Start Postman
3. Import the [Quick Start postman collection](https://github.com/GrindrodBank/tilkynna/blob/master/postman/Tilkynna%20Quickstart.postman_collection.json)
4. Import the [Postman environment file](https://github.com/GrindrodBank/tilkynna/blob/master/postman/Tilkynna.postman_environment.json)
5. The Quick start postman requests fail because the environment variables are not set correctly

**Expected behavior**
The Postman environment for the Quick Start should result in postman requests that succeed.

**Screenshots**
![Screenshot from 2019-05-13 12-12-00](https://user-images.githubusercontent.com/1935321/57613940-6571e880-7578-11e9-8cc0-f6c7ea595026.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Postman: Postman for Linux, , version 6.7.1, linux 4.15.0-48-generic / x64

**Smartphone (please complete the following information):**
n/a

**Additional context**
none

**Comment by melissapalmer** [comment]
Will start looking at this now, see branch https://github.com/GrindrodBank/tilkynna/tree/9-postman-environment

**Comment by melissapalmer** [comment]
This has been corrected by PR #10
